version: "3.3"

services:
  webservice:
    image: nginx
    container_name: "webservice"
    volumes:
    - ./templates:/etc/nginx/templates
    - ./html:/var/www/html
    - ./moodledata:/var/www/moodledata
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    networks: ["server"]
    restart: "always"
    ports:
        - "80:80"
        # - "443:443"
        
  database:
    image: postgres:13-alpine
    container_name: "postgres"
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=moodle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks: ["server"]

  php_fpm:
    build: php-fpm-8.0
    container_name: "php_fpm"
    restart: unless-stopped
    networks: ["server"]
    volumes:
    - ./html:/var/www/html
    - ./moodledata:/var/www/moodledata
    - ./php-conf/php.ini:/usr/local/etc/php/php.ini
networks:
    server:
        external: true

volumes:
    certs:
    vhost:
    html: